In [4]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [6]:
import numpy as np
arr1=np.array([1,2,3,4,5])
k=arr1.reshape(1,5)
print(k.shape)


(1, 5)


In [8]:
import numpy as np
arr=np.array([[1,2,3,4],[4,5,6,7]])
print(arr)
print(arr.shape)

[[1 2 3 4]
 [4 5 6 7]]
(2, 4)


In [1]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [4]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(arr.shape)

[1 2 3 4]
(4,)


In [19]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


(2, 3)
2
6
int64


In [13]:
import numpy as np
arr=np.arange(10,20,2).reshape(5,1)
print(arr)


[[10]
 [12]
 [14]
 [16]
 [18]]


In [15]:
import numpy as np
arr=np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
import numpy as np
arr=np.eye(4)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
